import { Injectable } from '@nestjs/common';
import { EventEmitter } from 'events';
import {
  VentilatorSettings,
  PatientModel,
  AsynchronyStatus,
  AsynchronyType,
  TelemetryData,
  DEFAULT_SETTINGS,
  DEFAULT_PATIENT,
} from '../common/dto/ventilator.dto';

interface SimulationState {
  time: number;           // Current simulation time in seconds
  phase: 'inspiration' | 'expiration';
  phaseTime: number;      // Time within current phase in seconds
  breathCount: number;
  
  // Physics State
  currentPressure: number; // Alveolar pressure (cmH2O)
  currentFlow: number;     // Flow rate (L/s)
  currentVolume: number;   // Lung volume above FRC (L)
  musclePressure: number;  // Pressure generated by patient muscles (cmH2O)
  
  settings: VentilatorSettings;
  patient: PatientModel;
  asynchrony: AsynchronyStatus;
  scenarioName: string;
  scenarioBlocks?: any[];
  
  // Asynchrony resolution tracking
  baselineSettings: VentilatorSettings | null;
  currentAsynchronyEvent: any | null;
  
  // Telemetry Buffers for batching (10Hz)
  pressureBuffer: number[];
  flowBuffer: number[];
  volumeBuffer: number[];
}

@Injectable()
export class SimulationService extends EventEmitter {
  private states: Map<string, SimulationState> = new Map();
  private intervals: Map<string, NodeJS.Timeout> = new Map();
  private callbacks: Map<string, (data: TelemetryData) => void> = new Map();

  // Sampling rate
  private readonly SAMPLE_RATE = 50; // 50 Hz
  private readonly DT = 1 / this.SAMPLE_RATE; // 0.02 seconds

  /**
   * Start simulation for a station
   */
  startSimulation(
    stationId: string,
    scenarioName: string,
    onTelemetry: (data: TelemetryData) => void,
  ): void {
    this.stopSimulation(stationId);

    const state: SimulationState = {
      time: 0,
      phase: 'inspiration',
      phaseTime: 0,
      breathCount: 0,
      currentPressure: DEFAULT_SETTINGS.peep,
      currentFlow: 0,
      currentVolume: 0,
      musclePressure: 0,
      settings: { ...DEFAULT_SETTINGS },
      patient: { ...DEFAULT_PATIENT },
      asynchrony: { active: false, type: null },
      scenarioName,
      scenarioBlocks: [],
      baselineSettings: null,
      currentAsynchronyEvent: null,
      pressureBuffer: [],
      flowBuffer: [],
      volumeBuffer: [],
    };

    this.states.set(stationId, state);
    this.callbacks.set(stationId, onTelemetry);

    const interval = setInterval(() => {
      this.simulationTick(stationId);
    }, this.DT * 1000);

    this.intervals.set(stationId, interval);
  }

  /**
   * Stop simulation for a station
   */
  stopSimulation(stationId: string): void {
    const interval = this.intervals.get(stationId);
    if (interval) {
      clearInterval(interval);
      this.intervals.delete(stationId);
    }
    this.states.delete(stationId);
    this.callbacks.delete(stationId);
  }

  /**
   * Update ventilator settings
   */
  updateSettings(stationId: string, settings: Partial<VentilatorSettings>): void {
    const state = this.states.get(stationId);
    if (!state) return;

    for (const key of Object.keys(settings)) {
       const typedKey = key as keyof VentilatorSettings;
       if (state.settings[typedKey] !== settings[typedKey]) {
           const prev = state.settings[typedKey] as number;
           const curr = settings[typedKey] as number;
           this.emit('setting_changed', stationId, typedKey, prev, curr, state.asynchrony.active, state.asynchrony.type);
       }
    }

    state.settings = { ...state.settings, ...settings };
  }

  /**
   * Update patient parameters with sanitization
   */
  updatePatientParameters(stationId: string, parameters: Partial<PatientModel>): void {
    const state = this.states.get(stationId);
    if (!state) return;

    // Sanitize and update
    if (parameters.resistance !== undefined) {
      state.patient.resistance = Math.max(0.5, parameters.resistance);
    }
    
    if (parameters.compliance !== undefined) {
      // Store as mL/cmH2O (DTO units). Physics converts to L/cmH2O via /1000.
      state.patient.compliance = Math.max(1, parameters.compliance); 
    }

    if (parameters.effort !== undefined) state.patient.effort = Math.max(0, parameters.effort);
    if (parameters.spontaneousRate !== undefined) state.patient.spontaneousRate = Math.max(0, parameters.spontaneousRate);
  }

  /**
   * Apply scenario events scheduled timeline
   */
  applyScenarioEvents(stationId: string, blocks: any[]): void {
     const state = this.states.get(stationId);
     if (state) {
        state.scenarioBlocks = [...blocks];
        // Reset timers so that relative timestamps (e.g. at 30s) trigger properly!
        state.time = 0;
        state.phaseTime = 0;
        state.breathCount = 0;
        state.phase = 'expiration';
     }
  }

  /**
   * Get current state
   */
  getState(stationId: string): SimulationState | undefined {
    return this.states.get(stationId);
  }

  /**
   * Inject asynchrony
   */
  injectAsynchrony(stationId: string, type: AsynchronyType | null): void {
    const state = this.states.get(stationId);
    if (state) {
      if (type !== null && state.asynchrony.type !== type) {
         state.asynchrony = { active: true, type };
         state.baselineSettings = { ...state.settings };
         state.currentAsynchronyEvent = null; // Manual injection
      } else if (type === null) {
         state.asynchrony = { active: false, type: null };
         state.baselineSettings = null;
         state.currentAsynchronyEvent = null;
      }
    }
  }

  /**
   * Check if student fixed the asynchrony by adjusting settings
   */
  private checkIfAsynchronyFixed(state: SimulationState): boolean {
    if (!state.asynchrony.active || !state.asynchrony.type || !state.baselineSettings) return false;
    
    const current = state.settings;
    const base = state.baselineSettings;

    switch (state.asynchrony.type) {
      case 'INEFFECTIVE_TRIGGER':
        // Student fixed if they reduced trigger threshold by at least 1.0
        // OR reduced IPAP by at least 2.0 (reducing over-assistance)
        return (current.trigger <= base.trigger - 1.0 + 0.001) || (current.ipap <= base.ipap - 2 + 0.001);

      case 'DOUBLE_TRIGGER':
      case 'PREMATURE_CYCLING':
        // Student fixed if they lengthened inspiration time (Ti) by at least 0.2s
        return current.ti >= base.ti + 0.2 - 0.001;

      case 'FLOW_MISMATCH':
        // Fixed if they increased IPAP by 2 (augmenting flow/pressure support)
        return current.ipap >= base.ipap + 2 - 0.001;

      default:
        return false;
    }
  }

  /**
   * Main simulation tick
   */
  private simulationTick(stationId: string): void {
    const state = this.states.get(stationId);
    const callback = this.callbacks.get(stationId);
    if (!state || !callback) return;

    // 1. Advance Time
    state.time += this.DT;
    state.phaseTime += this.DT;

    // 2. Manage Phase Transitions
    this.managePhases(state);

    // 3. Calculate Physics (RC Model)
    this.calculatePhysics(state);

    // 4. Process Scheduled Scenario Events
    this.processScheduledEvents(stationId, state);

    // 4.5. Check if the user fixed the currently active asynchrony
    if (this.checkIfAsynchronyFixed(state)) {
       const resolvedType = state.asynchrony.type;
       state.asynchrony = { active: false, type: null };
       state.baselineSettings = null;
       if (state.currentAsynchronyEvent) {
          state.currentAsynchronyEvent._resolved = true;
          state.currentAsynchronyEvent = null;
       }
       this.emit('asynchrony_resolved', stationId, resolvedType);
    }

    // 5. Apply Asynchrony Effects
    this.applyAsynchrony(state);

    // 6. Send Telemetry (Batched)
    // Convert units for frontend:
    // Pressure: cmH2O (no conversion)
    // Flow: L/s -> L/min (x60)
    // Volume: L -> mL (x1000)
    
    // Add current points to batch buffers
    state.pressureBuffer.push(Math.round(state.currentPressure * 10) / 10);
    state.flowBuffer.push(Math.round(state.currentFlow * 60 * 10) / 10);
    state.volumeBuffer.push(Math.round(state.currentVolume * 1000));

    // Send payload every 5 ticks (100ms / 10Hz)
    if (state.pressureBuffer.length >= 5) {
      const telemetry: TelemetryData = {
        timestamp: Date.now(),
        pressure: [...state.pressureBuffer],
        flow: [...state.flowBuffer],
        volume: [...state.volumeBuffer],
        settings: state.settings,
        asynchrony: state.asynchrony,
        scenarioName: state.scenarioName,
      };

      callback(telemetry);

      // Clear batch buffers
      state.pressureBuffer = [];
      state.flowBuffer = [];
      state.volumeBuffer = [];
    }
  }

  /**
   * Manage breath phases (Inspiration <-> Expiration)
   */
  private managePhases(state: SimulationState): void {
    const { settings } = state;
    const breathPeriod = 60 / settings.rr; // seconds per breath

    if (state.phase === 'inspiration') {
      if (state.phaseTime >= settings.ti) {
        state.phase = 'expiration';
        state.phaseTime = 0;
      }
    } else {
      const expiratoryTime = breathPeriod - settings.ti;
      if (state.phaseTime >= expiratoryTime) {
        let isFailedTrigger = false;

        // INEFFECTIVE_TRIGGER logic: Every 3rd breath fails to switch to inspiration
        if (state.asynchrony.active && state.asynchrony.type === 'INEFFECTIVE_TRIGGER') {
           if (state.breathCount % 3 === 2) {
              isFailedTrigger = true;
           }
        }

        if (isFailedTrigger) {
           // Skip inspiration. Machine stays in expiration waiting for the NEXT triggering event
           state.phaseTime = 0;
           state.breathCount++; // count the failed attempt
        } else {
           state.phase = 'inspiration';
           state.phaseTime = 0;
           state.breathCount++;
        }
      }
    }
  }

  /**
   * Calculate physics using Analytical Solution for RC Circuit
   * Equation: V(t) = V_target + (V_initial - V_target) * e^(-dt/tau)
   */
  private calculatePhysics(state: SimulationState): void {
    const { settings, patient } = state;
    
    // Physics Parameters
    // Resistance R [cmH2O / (L/s)]
    const R = patient.resistance; 
    
    // Compliance C [L / cmH2O]
    // Note: PatientModel usually stores compliance in mL/cmH2O, so we convert to L/cmH2O
    const C = patient.compliance / 1000; 

    const tau = R * C; // Time constant (seconds)

    // Calculate Target Pressure (P_driving) based on mode
    let P_vent = 0;
    
    if (state.phase === 'inspiration') {
      switch (settings.mode) {
        case 'PC-CMV':
        case 'PC-SIMV':
        case 'PSV':
          P_vent = settings.peep + settings.pinsp;
          break;
        case 'CPAP':
          P_vent = settings.peep;
          break;
        case 'VC-CMV':
        case 'VC-SIMV':
          // For Volume Control, we control flow directly
          const targetFlow = (settings.vt / 1000) / settings.ti; // L/s
          state.currentFlow = targetFlow;
          state.currentVolume += targetFlow * this.DT;
          
          // P_vent = Flow * R + Volume / C + PEEP (approx)
          const P_resistive = state.currentFlow * R;
          const P_elastic = state.currentVolume / C;
          state.currentPressure = P_resistive + P_elastic + settings.peep;
          return; 
      }
    } else {
      // Expiration
      P_vent = settings.peep;
    }

    // Calculate Muscle Pressure (P_mus)
    const P_mus = this.calculateMusclePressure(state, state.time);
    state.musclePressure = P_mus;

    // Total Driving Pressure acting on the lung
    // P_driving = P_vent + P_mus
    const P_driving = P_vent + P_mus;

    // Calculate Target Volume (Asymptote)
    // V_target is the equilibrium volume at the current pressure
    // V_target = C * P_driving
    const V_target = C * P_driving; 
    
    // Previous Volume
    const V_initial = state.currentVolume;
    
    // Exact Discretization Step
    // V(t+dt) = V_target + (V(t) - V_target) * exp(-dt/tau)
    const decay = Math.exp(-this.DT / tau);
    const V_next = V_target + (V_initial - V_target) * decay;

    // Update State
    state.currentVolume = V_next;
    
    // Back-calculate Flow
    // Flow = (V_next - V_initial) / dt
    state.currentFlow = (V_next - V_initial) / this.DT;

    // Calculate Alveolar Pressure
    // P_alv = V / C
    const P_alv = state.currentVolume / C;
    
    // In PC mode, ventilator controls airway pressure directly (square wave)
    state.currentPressure = P_vent; 
  }

  /**
   * Calculate Muscle Pressure (P_mus)
   */
  private calculateMusclePressure(state: SimulationState, time: number): number {
    const { effort, spontaneousRate } = state.patient;
    
    if (spontaneousRate <= 0 || effort <= 0) return 0;

    // Frequency in Hz
    const freq = spontaneousRate / 60;
    
    // Simple sinusoidal effort
    // P_mus = -1 * effort * sin(2 * PI * freq * time)
    // We add a shift so it's mostly negative (inspiratory effort) during demand?
    // User requested: -1 * effort * sin(...)
    // This will oscillate between -effort and +effort.
    return -1 * effort * Math.sin(2 * Math.PI * freq * time);
  }

  private applyAsynchrony(state: SimulationState): void {
    if (!state.asynchrony.active) return;
    
    if (state.asynchrony.type === 'FLOW_MISMATCH') {
       if (state.phase === 'inspiration' && state.settings.mode.startsWith('VC')) {
          // Turbulence increases resistance reading
          state.currentPressure += 5 * Math.random();
       }
    }
    else if (state.asynchrony.type === 'INEFFECTIVE_TRIGGER') {
       // Visual representation of patient effort that ventilator ignored.
       // The breath was dropped (phase stayed 'expiration') 
       // When breathCount was incremented, previous '2' became '0' % 3.
       if (state.phase === 'expiration' && state.phaseTime < 0.25 && (state.breathCount % 3 === 0)) {
           const t = state.phaseTime / 0.25;
           const patientEffort = Math.sin(t * Math.PI) * 2.5; // Up to 2.5 cmH2O dip in circuit pressure
           
           state.currentPressure -= patientEffort;
           // Slight inward flow due to effort against closed expiratory valve bias flow
           state.currentFlow += patientEffort * 0.1; 
       }
    }
    else if (state.asynchrony.type === 'DOUBLE_TRIGGER') {
       // Patient wants more volume, immediately triggering a SECOND strong artificial breath 
       // during early expiration. This yields a second pressure peak.
       if (state.phase === 'expiration' && state.phaseTime < 0.4) {
           const t = state.phaseTime / 0.4;
           const peakPressure = (state.settings.pinsp || (state.settings.ipap - state.settings.peep));
           state.currentPressure += peakPressure * Math.sin(t * Math.PI) * 0.8;
           
           // Limit stacking volume to realistic TLC (ex. 1500ml total) to prevent infinite accumulation
           if (state.currentVolume < 1.5) {
               state.currentVolume += 0.02 * Math.sin(t * Math.PI); 
           }
           state.currentFlow += 0.5 * Math.sin(t * Math.PI); // Positive inspiratory flow
       }
    }
    else if (state.asynchrony.type === 'PREMATURE_CYCLING') {
       // Ventilator cycles to expiration BEFORE patient finishes inspiration.
       // Patient still pulls air, leading to positive flow despite expiration mode, and negative pressure.
       if (state.phase === 'expiration' && state.phaseTime < 0.3) {
           const t = state.phaseTime / 0.3;
           state.currentFlow += 0.8 * (1 - t);
           state.currentPressure -= 2 * (1 - t);
       }
    }
  }

  private processScheduledEvents(stationId: string, state: SimulationState): void {
     if (!state.scenarioBlocks || state.scenarioBlocks.length === 0) return;

     const currentTime = state.time;
     
     // Find events that should be active right now
     for (const iterBlock of state.scenarioBlocks) {
         if (iterBlock.type === 'ASYNCHRONY' && iterBlock.asynchronyType) {
             const startTime = iterBlock.startTime;
             const duration = iterBlock.duration || 30; // 30s default
             const endTime = startTime + duration;

             if (currentTime >= startTime && currentTime <= endTime) {
                 if (state.asynchrony.type !== iterBlock.asynchronyType && !iterBlock._resolved) {
                     state.asynchrony = { active: true, type: iterBlock.asynchronyType };
                     state.baselineSettings = { ...state.settings };
                     state.currentAsynchronyEvent = iterBlock;
                 }
             } else if (currentTime > endTime && state.asynchrony.type === iterBlock.asynchronyType) {
                 // Stop the asynchrony when duration is over
                 const expiredType = state.asynchrony.type;
                 state.asynchrony = { active: false, type: null };
                 state.baselineSettings = null;
                 state.currentAsynchronyEvent = null;
                 // Notify system that it ended (so analytics stop logging it as active)
                 this.emit('asynchrony_resolved', stationId, expiredType);
             }
         }
         
         const startTime = iterBlock.startTime;
         if (currentTime >= startTime && !iterBlock._applied) {
             // Apply Ventilator Settings changes
             if (iterBlock.parameterChanges && Object.keys(iterBlock.parameterChanges).length > 0) {
                 state.settings = {
                    ...state.settings,
                    ...iterBlock.parameterChanges
                 };
             }
             
             // Apply Patient Physics changes (Compliance, Resistance, etc.)
             if (iterBlock.compliance !== undefined) {
                 state.patient.compliance = Math.max(1, iterBlock.compliance);
             }
             if (iterBlock.resistance !== undefined) {
                 state.patient.resistance = Math.max(0.5, iterBlock.resistance);
             }
             
             iterBlock._applied = true;
         }
     }
  }
}
