import { Injectable } from '@nestjs/common';
import {
  VentilatorSettings,
  PatientModel,
  AsynchronyStatus,
  AsynchronyType,
  TelemetryData,
  DEFAULT_SETTINGS,
  DEFAULT_PATIENT,
} from '../common/dto/ventilator.dto';

interface SimulationState {
  time: number;           // Current simulation time in seconds
  phase: 'inspiration' | 'expiration';
  phaseTime: number;      // Time within current phase in seconds
  breathCount: number;
  
  // Physics State
  currentPressure: number; // Alveolar pressure (cmH2O)
  currentFlow: number;     // Flow rate (L/s)
  currentVolume: number;   // Lung volume above FRC (L)
  musclePressure: number;  // Pressure generated by patient muscles (cmH2O)
  
  settings: VentilatorSettings;
  patient: PatientModel;
  asynchrony: AsynchronyStatus;
  scenarioName: string;
  scenarioEvents?: any[]; // Keep any to avoid circular import for now
  
  // Telemetry Buffers for batching (10Hz)
  pressureBuffer: number[];
  flowBuffer: number[];
  volumeBuffer: number[];
}

@Injectable()
export class SimulationService {
  private states: Map<string, SimulationState> = new Map();
  private intervals: Map<string, NodeJS.Timeout> = new Map();
  private callbacks: Map<string, (data: TelemetryData) => void> = new Map();

  // Sampling rate
  private readonly SAMPLE_RATE = 50; // 50 Hz
  private readonly DT = 1 / this.SAMPLE_RATE; // 0.02 seconds

  /**
   * Start simulation for a station
   */
  startSimulation(
    stationId: string,
    scenarioName: string,
    onTelemetry: (data: TelemetryData) => void,
  ): void {
    this.stopSimulation(stationId);

    const state: SimulationState = {
      time: 0,
      phase: 'inspiration',
      phaseTime: 0,
      breathCount: 0,
      currentPressure: DEFAULT_SETTINGS.peep,
      currentFlow: 0,
      currentVolume: 0,
      musclePressure: 0,
      settings: { ...DEFAULT_SETTINGS },
      patient: { ...DEFAULT_PATIENT },
      asynchrony: { active: false, type: null },
      scenarioName,
      scenarioEvents: [],
      pressureBuffer: [],
      flowBuffer: [],
      volumeBuffer: [],
    };

    this.states.set(stationId, state);
    this.callbacks.set(stationId, onTelemetry);

    const interval = setInterval(() => {
      this.simulationTick(stationId);
    }, this.DT * 1000);

    this.intervals.set(stationId, interval);
  }

  /**
   * Stop simulation for a station
   */
  stopSimulation(stationId: string): void {
    const interval = this.intervals.get(stationId);
    if (interval) {
      clearInterval(interval);
      this.intervals.delete(stationId);
    }
    this.states.delete(stationId);
    this.callbacks.delete(stationId);
  }

  /**
   * Update ventilator settings
   */
  updateSettings(stationId: string, settings: Partial<VentilatorSettings>): void {
    const state = this.states.get(stationId);
    if (state) {
      state.settings = { ...state.settings, ...settings };
    }
  }

  /**
   * Update patient parameters with sanitization
   */
  updatePatientParameters(stationId: string, parameters: Partial<PatientModel>): void {
    const state = this.states.get(stationId);
    if (!state) return;

    // Sanitize and update
    if (parameters.resistance !== undefined) {
      state.patient.resistance = Math.max(0.5, parameters.resistance);
    }
    
    if (parameters.compliance !== undefined) {
      // Input is mL/cmH2O, convert to L/cmH2O if needed? 
      // Requirement: "Konwertować jednostki: Nauczyciel wysyła Compliance w `mL/cmH2O`, ale fizyka używa `L/cmH2O`. Podziel wartość przez 1000."
      // BUT SimulationState.patient usually holds raw values from DTO? 
      // Let's check DTO. DTO usually has mL/cmH2O.
      // So in internal state we store PatientModel which is DTO.
      // So we store mL/cmH2O. Physical calc converts it.
      // Wait, "fizyka używa L/cmH2O". 
      // If `state.patient` is `PatientModel` (DTO), then it stores mL/cmH2O.
      // So here we should just store it as is (or sanitized), and `calculatePhysics` does the divide by 1000.
      // OR does the user want us to convert it HERE?
      // "Nauczyciel wysyła Compliance w mL/cmH2O... Podziel wartość przez 1000"
      // If I divide here, then `state.patient.compliance` will be in L/cmH2O.
      // But `PatientModel` type suggests it matches DTO which usually implies standard units (mL).
      // If I change it to L, then it might mismatch type expectation elsewhere.
      // However, `SimulationState` has `patient: PatientModel`.
      // Let's assume we store it as is (mL) to keep DTO consistent, so I will NOT divide here, 
      // but ensure I divide in `calculatePhysics`.
      // WAIT. "Nauczyciel wysyła... Podziel wartość przez 1000".
      // Maybe the user implies the input `parameters` is from JSON/API and I should save it.
      // Let's assume the user wants me to handle the conversion logic in `calculatePhysics` effectively,
      // or if they want `state.patient.compliance` to be L/cmH2O, I should probably check if I refactored `PatientModel`? 
      // I did NOT refactor `PatientModel` in DTO. It says comments: "mL/cmH2O".
      // So I should keep it mL/cmH2O in state, and divide in physics.
      
      // Let's just ensure positive value.
      state.patient.compliance = Math.max(1, parameters.compliance); 
    }

    if (parameters.effort !== undefined) state.patient.effort = Math.max(0, parameters.effort);
    if (parameters.spontaneousRate !== undefined) state.patient.spontaneousRate = Math.max(0, parameters.spontaneousRate);
  }

  /**
   * Apply scenario events scheduled timeline
   */
  applyScenarioEvents(stationId: string, events: any[]): void {
     const state = this.states.get(stationId);
     if (state) {
        state.scenarioEvents = [...events];
     }
  }

  /**
   * Get current state
   */
  getState(stationId: string): SimulationState | undefined {
    return this.states.get(stationId);
  }

  /**
   * Inject asynchrony
   */
  injectAsynchrony(stationId: string, type: AsynchronyType | null): void {
    const state = this.states.get(stationId);
    if (state) {
      state.asynchrony = { active: type !== null, type };
    }
  }

  /**
   * Main simulation tick
   */
  private simulationTick(stationId: string): void {
    const state = this.states.get(stationId);
    const callback = this.callbacks.get(stationId);
    if (!state || !callback) return;

    // 1. Advance Time
    state.time += this.DT;
    state.phaseTime += this.DT;

    // 2. Manage Phase Transitions
    this.managePhases(state);

    // 3. Calculate Physics (RC Model)
    this.calculatePhysics(state);

    // 4. Process Scheduled Scenario Events
    this.processScheduledEvents(state);

    // 5. Apply Asynchrony Effects
    this.applyAsynchrony(state);

    // 6. Send Telemetry (Batched)
    // Convert units for frontend:
    // Pressure: cmH2O (no conversion)
    // Flow: L/s -> L/min (x60)
    // Volume: L -> mL (x1000)
    
    // Add current points to batch buffers
    state.pressureBuffer.push(Math.round(state.currentPressure * 10) / 10);
    state.flowBuffer.push(Math.round(state.currentFlow * 60 * 10) / 10);
    state.volumeBuffer.push(Math.round(state.currentVolume * 1000));

    // Send payload every 5 ticks (100ms / 10Hz)
    if (state.pressureBuffer.length >= 5) {
      const telemetry: TelemetryData = {
        timestamp: Date.now(),
        pressure: [...state.pressureBuffer],
        flow: [...state.flowBuffer],
        volume: [...state.volumeBuffer],
        settings: state.settings,
        asynchrony: state.asynchrony,
        scenarioName: state.scenarioName,
      };

      callback(telemetry);

      // Clear batch buffers
      state.pressureBuffer = [];
      state.flowBuffer = [];
      state.volumeBuffer = [];
    }
  }

  /**
   * Manage breath phases (Inspiration <-> Expiration)
   */
  private managePhases(state: SimulationState): void {
    const { settings } = state;
    const breathPeriod = 60 / settings.rr; // seconds per breath

    if (state.phase === 'inspiration') {
      if (state.phaseTime >= settings.ti) {
        state.phase = 'expiration';
        state.phaseTime = 0;
      }
    } else {
      const expiratoryTime = breathPeriod - settings.ti;
      if (state.phaseTime >= expiratoryTime) {
        state.phase = 'inspiration';
        state.phaseTime = 0;
        state.breathCount++;
      }
    }
  }

  /**
   * Calculate physics using Analytical Solution for RC Circuit
   * Equation: V(t) = V_target + (V_initial - V_target) * e^(-dt/tau)
   */
  private calculatePhysics(state: SimulationState): void {
    const { settings, patient } = state;
    
    // Physics Parameters
    // Resistance R [cmH2O / (L/s)]
    const R = patient.resistance; 
    
    // Compliance C [L / cmH2O]
    // Note: PatientModel usually stores compliance in mL/cmH2O, so we convert to L/cmH2O
    const C = patient.compliance / 1000; 

    const tau = R * C; // Time constant (seconds)

    // Calculate Target Pressure (P_driving) based on mode
    let P_vent = 0;
    
    if (state.phase === 'inspiration') {
      switch (settings.mode) {
        case 'PC-CMV':
        case 'PC-SIMV':
        case 'PSV':
          P_vent = settings.peep + settings.pinsp;
          break;
        case 'CPAP':
          P_vent = settings.peep;
          break;
        case 'VC-CMV':
        case 'VC-SIMV':
          // For Volume Control, we control flow directly
          const targetFlow = (settings.vt / 1000) / settings.ti; // L/s
          state.currentFlow = targetFlow;
          state.currentVolume += targetFlow * this.DT;
          
          // P_vent = Flow * R + Volume / C + PEEP (approx)
          const P_resistive = state.currentFlow * R;
          const P_elastic = state.currentVolume / C;
          state.currentPressure = P_resistive + P_elastic + settings.peep;
          return; 
      }
    } else {
      // Expiration
      P_vent = settings.peep;
    }

    // Calculate Muscle Pressure (P_mus)
    const P_mus = this.calculateMusclePressure(state, state.time);
    state.musclePressure = P_mus;

    // Total Driving Pressure acting on the lung
    // P_driving = P_vent + P_mus
    const P_driving = P_vent + P_mus;

    // Calculate Target Volume (Asymptote)
    // V_target is the equilibrium volume at the current pressure
    // V_target = C * P_driving
    const V_target = C * P_driving; 
    
    // Previous Volume
    const V_initial = state.currentVolume;
    
    // Exact Discretization Step
    // V(t+dt) = V_target + (V(t) - V_target) * exp(-dt/tau)
    const decay = Math.exp(-this.DT / tau);
    const V_next = V_target + (V_initial - V_target) * decay;

    // Update State
    state.currentVolume = V_next;
    
    // Back-calculate Flow
    // Flow = (V_next - V_initial) / dt
    state.currentFlow = (V_next - V_initial) / this.DT;

    // Calculate Alveolar Pressure
    // P_alv = V / C
    const P_alv = state.currentVolume / C;
    
    // Calculate Ventilator Pressure (What the machine sees)
    // If flow is positive (Inspiration), P_vent is pushing.
    // P_vent_measured = P_alv + Flow * R
    // However, in PC mode, the ventilator CONTROLS P_vent, so it should be exactly targetPressure.
    // But let's show the physical interaction.
    // If P_mus is very strong (negative), it sucks air in, Flow increases.
    // P_vent should remain constant in PC mode (ideal voltage source).
    state.currentPressure = P_vent; 
    // Wait, if I set it to P_vent, I lose the visual of the pressure rise if I had it.
    // But PC mode IS square wave pressure.
    // If I want to match reality, P_vent is what sensors measure.
    // In PC mode, it measures the set pressure.
  }

  /**
   * Calculate Muscle Pressure (P_mus)
   */
  private calculateMusclePressure(state: SimulationState, time: number): number {
    const { effort, spontaneousRate } = state.patient;
    
    if (spontaneousRate <= 0 || effort <= 0) return 0;

    // Frequency in Hz
    const freq = spontaneousRate / 60;
    
    // Simple sinusoidal effort
    // P_mus = -1 * effort * sin(2 * PI * freq * time)
    // We add a shift so it's mostly negative (inspiratory effort) during demand?
    // User requested: -1 * effort * sin(...)
    // This will oscillate between -effort and +effort.
    return -1 * effort * Math.sin(2 * Math.PI * freq * time);
  }

  private applyAsynchrony(state: SimulationState): void {
    if (!state.asynchrony.active) return;
    
    // Simple implementations for visual feedback
    if (state.asynchrony.type === 'FLOW_MISMATCH') {
       if (state.phase === 'inspiration' && state.settings.mode.startsWith('VC')) {
          // Turbulence increases resistance reading
          state.currentPressure += 5 * Math.random();
       }
    }
  }

  private processScheduledEvents(state: SimulationState): void {
     if (!state.scenarioEvents || state.scenarioEvents.length === 0) return;

     const currentTime = state.time;
     
     // Find events that should be active right now
     // Scenario events have `time` (start time) and optionally `duration`
     for (const iterEvent of state.scenarioEvents) {
         if (iterEvent.type === 'asynchrony' && iterEvent.asynchronyType) {
             const startTime = iterEvent.time;
             const duration = iterEvent.duration || 30; // 30s default
             const endTime = startTime + duration;

             if (currentTime >= startTime && currentTime <= endTime) {
                 if (state.asynchrony.type !== iterEvent.asynchronyType) {
                     state.asynchrony = { active: true, type: iterEvent.asynchronyType };
                 }
             } else if (currentTime > endTime && state.asynchrony.type === iterEvent.asynchronyType) {
                 // Stop the asynchrony when duration is over
                 state.asynchrony = { active: false, type: null };
             }
         }
         
         if (iterEvent.type === 'setting_change' && iterEvent.settingChange) {
             const startTime = iterEvent.time;
             // Settings changes happen once at exact time
             // To prevent continuous triggering, we remove the event after applying or mark it done
             if (currentTime >= startTime && !iterEvent._applied) {
                 state.settings = {
                    ...state.settings,
                    [iterEvent.settingChange.parameter]: iterEvent.settingChange.value
                 };
                 iterEvent._applied = true;
             }
         }
     }
  }
}
